services:
  webooksmith-db:
    image: postgres:16-alpine
    container_name: webhooksmith_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: webhooksmith
      POSTGRES_USER: webhooksmith
      POSTGRES_PASSWORD: password # Change me
    ports:
      - 5432:5432
    volumes:
      # I recommend using an absolute path on the host, and that you back that directory up.
      - ./data:/var/lib/postgresql/data
    networks:
      - webhooksmith_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webhooksmith -d webhooksmith"]
      interval: 5s
      timeout: 5s
      retries: 20
  webooksmith-api:
    image: ghcr.io/zeilar/webhooksmith-api:latest
    container_name: webhooksmith_api
    restart: unless-stopped
    environment:
      DB_HOST: webhooksmith-db
      DB_PORT: 5432
      DB_NAME: webhooksmith
      DB_USER: webhooksmith
      DB_PASSWORD: password # Change me
      DB_LOGGING: false
      LOG_LEVEL: verbose
      PORT: 3030
      HOST: 0.0.0.0
      ALLOWED_ORIGINS: web,webhooksmith.angelin.foo
      COOKIE_DOMAIN: .angelin.foo # I recommend using a dot prefix if you use subdomains.
      SESSION_TTL: 604800000 # 7 days
      SWAGGER_ENABLED: false
      SWAGGER_PATH: /docs
      # Remove these after first setup, or if you need to recover the user.
      INITIAL_USERNAME: admin
      INITIAL_PASSWORD: password
    # Set up tables etc if they don't exist, I recommend letting the CLI do this.
    # You may remove this whole line after the initial setup, if not then be sure to backup data in case of updates.
    command: sh -c "pnpm db:migrate && node dist/main"
    ports:
      - 3030:3030
    depends_on:
      webhooksmith-db:
        condition: service_healthy
    networks:
      - webhooksmith_network
  webhooksmith-web:
    image: ghcr.io/zeilar/webhooksmith-web:latest
    container_name: webhooksmith_web
    restart: unless-stopped
    environment:
      API_URL: https://api-webhooksmith.angelin.foo
      SOCKET_URL: wss://api-webhooksmith.angelin.foo
    ports:
      - 3000:3000
    depends_on:
      - webhooksmith-api
    networks:
      - webhooksmith_network

networks:
  webhooksmith_network:
    name: webhooksmith_network
    external: false
